### ISSUE TITLE
Library not loaded: @rpath/libmkl_intel_ilp64.2.dylib

### ISSUE THREAD

**Issue by pcchen** [kaihsin/Cytnx#112]
Cannot find MKL library when importing cytnx.

No error during installation.
````
conda config --add channels conda-forge
conda create --channel conda-forge --name cy38 python=3.8 llvm-openmp
conda activate cy38
````

cytnx 0.7.6a is istalled
````
conda list|grep cytnx
cytnx                     0.7.6a           py38h01edc0c_0    kaihsinwu
````

MKL related packages are installed
````
conda list |grep mkl
blas                      1.0                         mkl
mkl                       2021.4.0           h89fa619_689    conda-forge
mkl-include               2022.1.0           h6bab518_928    conda-forge
mkl-service               2.4.0            py38haa1d401_0    conda-forge
mkl_fft                   1.3.1            py38h0834169_1    conda-forge
mkl_random                1.2.2            py38h1f261ad_0    conda-forge
````

Fail.
````
$ python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:47)
[Clang 12.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cytnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pcchen/miniconda3/envs/cy38/lib/python3.8/site-packages/cytnx/__init__.py", line 3, in <module>
    from .cytnx import *
ImportError: dlopen(/Users/pcchen/miniconda3/envs/cy38/lib/python3.8/site-packages/cytnx/cytnx.cpython-38-darwin.so, 2): Library not loaded: @rpath/libmkl_intel_ilp64.2.dylib
  Referenced from: /Users/pcchen/miniconda3/envs/cy38/lib/python3.8/site-packages/cytnx/cytnx.cpython-38-darwin.so
  Reason: image not found
````

**Comment by jeffry1829** [comment]
Hi! May you try conda update -c conda-forge mkl ?
Thanks!

**Comment by pcchen** [comment]
`conda update -c conda-forge mkl` seems to solve the problem.

Packages modified are documented below.
````
The following NEW packages will be INSTALLED:

  blas-devel         conda-forge/osx-64::blas-devel-3.9.0-16_osx64_mkl
  libblas            conda-forge/osx-64::libblas-3.9.0-16_osx64_mkl
  libcblas           conda-forge/osx-64::libcblas-3.9.0-16_osx64_mkl
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-9_3_0_h6c81a4c_23
  libgfortran5       conda-forge/osx-64::libgfortran5-9.3.0-h6c81a4c_23
  liblapack          conda-forge/osx-64::liblapack-3.9.0-16_osx64_mkl
  liblapacke         conda-forge/osx-64::liblapacke-3.9.0-16_osx64_mkl
  mkl-devel          conda-forge/osx-64::mkl-devel-2022.1.0-h694c41f_929

The following packages will be REMOVED:

  mkl_fft-1.3.1-py38h0834169_1
  mkl_random-1.2.2-py38h1f261ad_0
  numpy-base-1.23.1-py38h3b1a694_0

The following packages will be UPDATED:

  blas                              pkgs/main::blas-1.0-mkl --> conda-forge::blas-2.116-mkl
  freetype                                2.10.4-h4cff582_1 --> 2.10.4-h3f81eb7_2
  mkl                                 2021.4.0-h89fa619_689 --> 2022.1.0-h860c996_928
  setuptools                          63.4.2-py38h50d1736_0 --> 63.4.3-py38h50d1736_0

The following packages will be SUPERSEDED by a higher-priority channel:

  numpy              pkgs/main::numpy-1.23.1-py38h2e5f0a9_0 --> conda-forge::numpy-1.23.1-py38h604f2a5_0

The following packages will be DOWNGRADED:

  mkl-service                          2.4.0-py38haa1d401_0 --> 2.4.0-py38h9483e8e_0
````

**Comment by pcchen** [comment]
@jeffry1829 Do you have any idea why this happens? We can modify the conda install script?

Or, we need to "advise" user how to fix this by using `conda update -c conda-forge mkl`.

**Comment by jeffry1829** [comment]
Actually, I can’t figured out why this happened :(

**Comment by pcchen** [comment]
Encounter similar problem on Ubuntu@WSL2
* mambaforge is used.
* ubuntu 20.04

## WSL/ubuntu
```
conda config --add channels conda-forge
conda create --channel conda-forge --name cy38 python=3.8 _openmp_mutex=*=*_llvm
conda activate cy38
conda install -c kaihsinwu cytnx
```

```
conda list |grep cytnx
cytnx                     0.7.5a           py38h3fd9d12_0    kaihsinwu
```

```
conda list |grep mkl
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0            16_linux64_mkl    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblapacke                3.9.0            16_linux64_mkl    conda-forge
mkl                       2022.1.0           h84fe81f_915    conda-forge
mkl-devel                 2022.1.0           ha770c72_916    conda-forge
mkl-include               2022.1.0           h84fe81f_915    conda-forge
```

```
python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cytnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pcchen/mambaforge/envs/cy38/lib/python3.8/site-packages/cytnx/__init__.py", line 3, in <module>
    from .cytnx import *
ImportError: libmkl_intel_ilp64.so.1: cannot open shared object file: No such file or directory
>>>
```

```
conda update -c conda-forge mkl
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

```
conda update -c kaihsinwu cytnx
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

**Comment by pcchen** [comment]
`conda update -c conda-forge mkl` and `conda update -c kaihsinwu cytnx` all show **All requested packages already installed.**.....

Don't know how to fix this.

**Comment by pcchen** [comment]
If I try python=3.9. I fail to install....

````
 conda create --channel conda-forge --name cy39 python=3.9 _openmp_mutex=*=*_llvm
 conda activate cy39
$ conda install -c kaihsinwu cytnx
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
````

**Comment by pcchen** [comment]
If I use python=3.7, I encounter the same problem as python=3.8. And I cannot update mkl/cytnx either. **All requested packages already installed**....

**Comment by pcchen** [comment]
So I try miniconda. Basically the same problem occurs.

* python3.9 --> fail to install cytnx.
* python3.8  --> cannot find mkl, cannot update mkl/cytnx.

**Comment by pcchen** [comment]
So I "remove and reinstall ubuntu" on my WSL2. Then I install miniconda.

`conda install -c kaihsinwu cytnx` works and gives me 0.7.6a, but I still get
````
 python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cytnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pcchen/miniconda3/envs/cytnx/lib/python3.9/site-packages/cytnx/__init__.py", line 3, in <module>
    from .cytnx import *
ImportError: libmkl_intel_ilp64.so.2: cannot open shared object file: No such file or directory
````

**Comment by j9263178** [comment]
We have released the newer version with newer mkl lib, maybe this will resolve.
