### ISSUE TITLE
Failed to print an element

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#180]
The example in User Guide 7.7.1 cannot be run successfully. The code is

```
import cytnx
T = cytnx.UniTensor(cytnx.arange(9).reshape(3,3))
print(T.at([0,2]).value)
```

and here is the error message.

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(T.at([0,2]).value)
  File "/home/chiamin/miniconda3/envs/cytnx/lib/python3.8/site-packages/cytnx/utils.py", line 6, in wrapper
    return func(self,*args, **kwargs)
  File "/home/chiamin/miniconda3/envs/cytnx/lib/python3.8/site-packages/cytnx/UniTensor_conti.py", line 216, in at
    tmp_hclass = self.c_at(locator);
TypeError: Unable to convert function return value to a Python type! The signature was
	(self: cytnx.cytnx.UniTensor, locator: List[int]) -> cHclass

**Comment by manuschneider** [comment]
In Cytnx version 0.9.1 this example works fine for me

**Comment by chiamin** [comment]
My version is 0.9.0. Is there an easy way to update the version? I have run `conda update cytnx` but still in 0.9.0. Here is the output of `conda list cytnx`

cytnx                     0.9.0            py38h3fd9d12_0    kaihsinwu

**Comment by manuschneider** [comment]
I had to set up a new environment from scratch, conda update did not work for me either.

**Comment by kaihsin** [comment]
Actually I don't know why conda update won't work sometimes if anyone wants to investigate feel free

**Comment by kaihsin** [comment]
We should create another issue to address conda packaging. I will close this one
