### ISSUE TITLE
example/iTEBD/iTEBD*.py fail to run

### ISSUE THREAD

**Issue by pcchen** [kaihsin/Cytnx#36]
# Python example codes, `example/iTEBD/iTEBD*.py`, fail to run.

## Cytnx source code version:
commit f5af34cb952784611b162a0d25c88682558ef750

## Cytnx environment:
````
Python 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cytnx
>>> cytnx.__version__
'0.7.3'
````

### iTEBD.py
python iTEBD.py
````
  File "iTEBD.py", line 150, in <module>
    A = cytnx.Contract(lb_inv,A)
RuntimeError:
# Cytnx error occur at cytnx::Tensor cytnx::linalg::Tensordot_dg(const cytnx::Tensor &, const cytnx::Tensor &, const std::vector<cytnx_uint64> &, const std::vector<cytnx_uint64> &, const bool &)
# error: the index L=0 and R=1 have different dimension!

# file : /Users/kaywu/.pyenv/versions/anaconda3-2021.05/conda-bld/cytnx_1626211920932/work/src/linalg/Tensordot_dg.cpp (48)
````

### iTEBD_U1.py
python iTEBD_U1.py
````
Traceback (most recent call last):
  File "iTEBD_U1.py", line 46, in <module>
    A = cytnx.UniTensor([bdi,bdi,bd_mid.redirect()],rowrank=1,labels=[-1,0,-2]);
AttributeError: 'cytnx.cytnx.Bond' object has no attribute 'redirect'
````

### iTEBD_tag.py
python iTEBD_tag.py
````
Traceback (most recent call last):
  File "iTEBD_tag.py", line 136, in <module>
    la *= 1./Norm
RuntimeError:
# Cytnx error occur at virtual void cytnx::DenseUniTensor::Mul_(const cytnx::Scalar &)
# error: [ERROR] cannot perform arithmetic on tagged unitensor L.

# file : /Users/kaywu/.pyenv/versions/anaconda3-2021.05/conda-bld/cytnx_1626211920932/work/src/DenseUniTensor.cpp (781)
````

**Comment by kaihsin** [comment]
Hi, that commit is incomplete. Please try f8a45f9640f9994824848d51f63e07881e7a0eb5

**Comment by pcchen** [comment]
````
(test0) [pcchen@scopion iTEBD]$ git log
commit f8a45f9640f9994824848d51f63e07881e7a0eb5 (HEAD -> master, origin/master, origin/HEAD)
````

````
conda update -c kaihsinwu cytnx
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
````

I still got the same error.

**Comment by kaihsin** [comment]
@pcchen, please build the latest commit from source. We do not have nightly build on master, so conda update will not keep you updated from the master build. 

New features with v074 onward will be released to conda package shortly

**Comment by kaihsin** [comment]
v0.7.4 is now on conda 
https://github.com/kaihsin/Cytnx/tree/v0.7.4
