### ISSUE TITLE
Fail to load

### ISSUE THREAD

**Issue by pcchen** [kaihsin/Cytnx#8]
With cc450996b648f7d667b4bde5102440a5ab76b668

````
>>> import cytnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/cytnx/__init__.py", line 1, in <module>
    from .cytnx import *
ImportError: dlopen(/usr/local/cytnx/cytnx.cpython-37m-darwin.so, 2): Symbol not found: __ZN5cytnx14utils_internal19Complexmem_cpu_cdtdEPvS1_RKyb
  Referenced from: /usr/local/cytnx/cytnx.cpython-37m-darwin.so
  Expected in: flat namespace
 in /usr/local/cytnx/cytnx.cpython-37m-darwin.so
````

**Comment by kaihsin** [comment]
Fixed in the latest push 52d5082be343b0304ac77dd9b1a8a4791dac6d4e
